### ISSUE TITLE
Consider introduce fusion rules for prime fields

### ISSUE THREAD

**Issue by aspiwack** [adjoint-io/galois-field#9]
Taking the remainder is a potentially expensive computation.

So it may be worth it to consider adding fusion rules for consecutive arithmetic operations to eliminate intermediate remainder computations.

**Comment by Multramate** [comment]
Noted, and thank you. I will be sure to further optimise prime fields using fusion rules after the main issues (#2 and #8) are settled, and possibly do the same for extension fields. Would be wonderful if you could suggest some of these rules to start off - and maybe shed some light into other optimising strategies?

**Comment by aspiwack** [comment]
> and maybe shed some light into other optimising strategies?

Oh my! You make it sound like if you know what I'm talking about. I really don't, I'm just along for the ride. I'm suggesting random things which are crossing my mind.

But anyway, the thing I would consider would be: make sure that all the methods of the `Num` instance of prime fields are `{-# INLINE … #-}`. Then add rules such as

```haskell
((a `mod` n) * b) `mod` n = (a * b) `mod` n
(a * (b `mod` n)) `mod` n = (a * b) `mod` n
```

And something to make sure that the newtype data constructor doesn't block these rules. Maybe there is a better design, I'm not sure

 I'm not even sure it's worth doing. But it makes some intuitive sense that trying to reduce the number of `mod` that one has to do is useful. And I can't think of a way to do so besides GHC rewrite rules (I'd be interested in learning that there is though!)

**Comment by sdiehl** [comment]
In the `inversion` branch we went through and did a bunch of aggressive inlining, specialisation and put some functions in form for worker-wrapper optimisation. Take a look and see you see any obvious ones we missed.

https://github.com/adjoint-io/galois-field/compare/inversion

**Comment by Multramate** [comment]
It is probably very worth doing - I will add those two rules soon as a start. As Stephen said, we've added inlines to all the functions under the Num instance (and even some manual inlining).

**Comment by aspiwack** [comment]
I can't see anything obviously missing in the inversion branch, no.

**Comment by sdiehl** [comment]
Ok lovely. I'll close this out.

**Comment by aspiwack** [comment]
Isn't it a bit early for closing, though? The inversion branch contains all the inlining you want, probably, but no rewrite rules yet (unless such rules already exist in base?).

I mean, I'm ok if you'd rather close the issue and keep the thoughts about rewrite rules in your head. Or decide that you don't want rewrite rules. Or something. But I just want to make sure that we're all talking about the same thing here.

**Comment by sdiehl** [comment]
Quite a few optimisations landed in this PR 0add093885a0e7299be9dcbad5153e37fbd6abc4 . Curious if you have any more insights for low-hanging fruit.

**Comment by Multramate** [comment]
We did some experimentation with rules over the past week, and decided it's best to keep them in our heads for now. The current implementation does not use `mod` directly for prime field elements (it's only used in `fromInteger`), and there isn't a nice way to incorporate the rules given above. A rule we've tried is somewhere along the lines of `(a * b `mod` n) * c `mod` n = (a * b * c) `mod` n`, which would reduce the number of modulos for many repeated multiplications (say in exponentiation) - but making `a * b` smaller before multiplying with `c` actually gives a better performance, so this was scrapped as well. The current issue isn't with the performance of prime field operations, as they are already relatively fast (even with the many modulos), but with those of extension field operations - but again, this will be addressed in #8. Maybe a rule that we could add that we have not (which I just realised right now) is to replace `(^)` with our custom `pow`?

**Comment by aspiwack** [comment]
> but making `a * b` smaller before multiplying with `c` actually gives a better performance

This is very interesting. I suppose there always was a tension between the two. But I would have assumed that removing `mod`-s would win nonetheless.

> Curious if you have any more insights for low-hanging fruit.

Not particularly, no, I'm afraid. To be honest, I opened this issue because I was curious. I'm not really knowledgeable in these matters.

**Comment by Bodigrim** [comment]
> This is very interesting. I suppose there always was a tension between the two. But I would have assumed that removing `mod`-s would win nonetheless.

Assuming for simplicity that all inputs fit a machine word, for ``(a * b `mod` m) * c `mod` m`` we execute:

* multiply two words `a * b` producing a double-word result `r0,r1` (least significant word first),
* divide double word `r0,r1` by `m` producing a single-word remainder `r2`,
* multiply two words `r2 * c` producing a double-word results `r3,r4`,
* divide double word `r3,r4` by `m` producing a single-word remainder `r`.

Overall 2 multiplications and 2 divisions.

For ``(a * b * c) `mod` m`` we execute:

* multiply two words `a * b` producing a double-word result `r0,r1`,
* multiply `r0 * c` producing a double-word result `r2,r3`,
* multiply `r1 * c` producing a double-word result `r4,r5`,
* add `r2,r3,0 + 0,r4,r5` producing `r6,r7,r8` - a product of `a * b * c`,
* divide double word `r7,r8` by `m` producing a single-word remainder `r9`,
* divide double word `r6,r9` by `m` producing a single-word remainder `r`.

Overall 3 multiplications and 2 divisions and more allocations.

> Curious if you have any more insights for low-hanging fruit.

Did you consider using [`Math.NumberTheory.Moduli.Class`](http://hackage.haskell.org/package/arithmoi-0.9.0.0/docs/Math-NumberTheory-Moduli-Class.html)? I suspect that it is faster (cf. [this discussion on performance of modular multiplications](https://github.com/Bodigrim/arithmoi/issues/160)) because of two reasons:

* GHC cannot deduce that modular multiplication is strict in both arguments without explicit bangs.

* When modulo fits a machine word we can invoke magic hash and completely avoid allocations/calls to `libgmp`.

**Comment by Multramate** [comment]
> Did you consider using [`Math.NumberTheory.Moduli.Class`](http://hackage.haskell.org/package/arithmoi-0.9.0.0/docs/Math-NumberTheory-Moduli-Class.html)?

We did - it is indeed faster, but the increase in speed is rather slight and pretty much unnoticeable, so we decided not to introduce a large dependency on `arithmoi`. Benchmarking on my machine shows that `product [1 .. 10^7]` takes 0.18s with `galois-field` and 0.14s with `arithmoi`, and `sum [1 .. 10^7]` takes 0.11s with `galois-field` and 0.10s with `arithmoi`. I've also tried comparing `pow` and `powMod` and the benchmarks show a slight speed decrease with `arithmoi`.

The current main issue is the speed of `BinaryField` arithmetic (and to some extent `ExtensionField` arithmetic and square roots), not so much `PrimeField`. I will look into `BangPatterns` and `MagicHash` when speed becomes an issue in `PrimeField` - thank you.

**Comment by Multramate** [comment]
This issue should be mostly settled and will be closed.

**Comment by Bodigrim** [comment]
> We did - it is indeed faster, but the increase in speed is rather slight and pretty much unnoticeable, so we decided not to introduce a large dependency on `arithmoi`. 

Sure, `arithmoi` is a kitchen sink and takes a while to build. But if this is the only blocker, I can most definitely separate modular arithmetic into a lightweight package on its own. Does it sound reasonable? I believe that sharing the same implementation would be mutually beneficial.

> The current main issue is the speed of `BinaryField` arithmetic

It is curious that you mentioned it now. This weekend I've been finalising patches to [`bitvec`](http://hackage.haskell.org/package/bitvec), adding a blazingly fast arithmetic of binary polynomials. Could you possibly give it a try before it is released? One can grab `bitvec-HEAD` from https://github.com/Bodigrim/bitvec and use [`Data.Bit.F2Poly`](https://github.com/Bodigrim/bitvec/blob/master/src/Data/Bit/F2Poly.hs).

**Comment by Multramate** [comment]
> Sure, arithmoi is a kitchen sink and takes a while to build. But if this is the only blocker, I can most definitely separate modular arithmetic into a lightweight package on its own. Does it sound reasonable? I believe that sharing the same implementation would be mutually beneficial.

Sounds good. I'll have another go at reusing the code again when the lightweight package is up, and will report any potential issues.

**Comment by Multramate** [comment]
Will continue this conversation over in a separate issue.
